filebeat.prospectors:
- type: docker
  combine_partial: true
  containers:
    path: "/usr/share/dockerlogs/data"
    stream: "stdout"
    ids:
      - "*"
# setup filebeat to send output to logstash
output.logstash:
  hosts: "10.148.0.18:5000"