version: '3'

services:
  filebeat:
    image: filebeat:1.0.0
    build:
      context: filebeat
      dockerfile: Dockerfile
    volumes:
      # needed to access all docker logs (read only) :
     - "/var/lib/docker/containers:/usr/share/dockerlogs/data"
      # needed to access additional informations about containers
     - "/var/run/docker.sock:/var/run/docker.sock"
